# Workflow to build and deploy OpenWrt packages for the PeDitXOS repository.
# This workflow is designed to run on a separate "builder" account and deploy to the main repository.

name: Build and Deploy PeDitXOS OpenWrt Packages

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at 00:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        openwrt_version:
          - 'openwrt-24.10'
          - 'master'
          - 'openwrt-23.05'
          - 'openwrt-22.03'
        target_subtarget:
          - 'ath79/generic'
          - 'bcm27xx/bcm2711'
          - 'ipq40xx/generic'
          - 'ipq806x/generic'
          - 'ipq807x/generic'
          - 'lantiq/xrx200'
          - 'mediatek/filogic'
          - 'mvebu/cortexa9'
          - 'ramips/mt7621'
          - 'rockchip/armv8'
          - 'sunxi/cortexa7'
          - 'x86/64'
          - 'qualcommax/ipq5018'
          - 'qualcommax/ipq6018'
          - 'qualcommax/ipq8074'
          - 'realtek/generic'
          - 'mediatek/mt7622'
        
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        
      - name: Clone OpenWrt source code
        run: git clone --depth 1 --branch ${{ matrix.openwrt_version }} https://github.com/openwrt/openwrt.git openwrt

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y subversion libncurses5-dev gawk zlib1g-dev python3-dev python3-setuptools unzip wget libtool python3-pip rsync
          pip3 install pyelftools

      - name: Add custom feeds and generate config
        run: |
          cd openwrt
          
          # Add standard feeds
          echo 'src-git passwall_packages https://github.com/xiaorouji/openwrt-passwall-packages' >> feeds.conf.default
          echo 'src-git passwall_peditx https://github.com/peditx/openwrt-passwall' >> feeds.conf.default
          echo 'src-git passwall2_peditx https://github.com/peditx/openwrt-passwall2' >> feeds.conf.default
          
          # Manually clone problematic LuCI repos directly into the package directory
          git clone --depth 1 https://github.com/peditx/luci-app-themeswitch.git ./package/luci-app-themeswitch
          git clone --depth 1 https://github.com/peditx/luci-theme-peditx.git ./package/luci-theme-peditx
          git clone --depth 1 https://github.com/peditx/luci-theme-carbonpx.git ./package/luci-theme-carbonpx

          # Update and install feeds
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          
          # Create a minimal .config with just the target
          TARGET_MAIN="${{ matrix.target_subtarget }}"
          TARGET=$(echo ${TARGET_MAIN} | cut -d '/' -f 1)
          SUBTARGET=$(echo ${TARGET_MAIN} | cut -d '/' -f 2)
          cat > .config << EOF
          CONFIG_TARGET_${TARGET}=y
          CONFIG_TARGET_${TARGET}_${SUBTARGET}=y
          EOF
          
          # Run 'defconfig' to generate a full, valid config
          make defconfig
          
          # Append custom selections
          cat >> .config << EOF
          CONFIG_DOWNLOAD_FOLDER=/opt/dl
          CONFIG_DEVEL=y
          CONFIG_CLEAN_IPKG=y
          CONFIG_SIGNED_PACKAGES=y
          CONFIG_PACKAGE_luci-app-themeswitch=y
          CONFIG_PACKAGE_luci-theme-peditx=y
          CONFIG_PACKAGE_luci-theme-carbonpx=y
          CONFIG_PACKAGE_luci-app-passwall=y
          CONFIG_PACKAGE_luci-app-passwall2=y
          EOF

      - name: Cache OpenWrt Downloads
        uses: actions/cache@v4
        with:
          path: openwrt/dl
          key: ${{ runner.os }}-${{ matrix.openwrt_version }}-dl-${{ hashFiles('openwrt/feeds.conf.default') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.openwrt_version }}-dl-

      - name: Decode usign private key
        run: |
          echo "${{ secrets.USIGN_PRIVATE_KEY }}" | base64 -d > openwrt/signing_key.pem
          echo "CONFIG_SIGNATURE_KEY=\"signing_key.pem\"" >> openwrt/.config

      - name: Download source code
        run: |
          cd openwrt
          make download -j$(nproc)
          
      - name: Cache Host Tools
        uses: actions/cache@v4
        with:
          path: openwrt/staging_dir/host
          key: ${{ runner.os }}-${{ matrix.openwrt_version }}-host-${{ hashFiles('openwrt/.config') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.openwrt_version }}-host-

      - name: Build host tools (usign)
        run: |
          cd openwrt
          make tools/install -j$(nproc) V=s
          
      - name: Build external packages
        run: |
          cd openwrt
          make package/index V=s

      - name: Organize packages for deployment
        run: |
          TARGET_DIR=$(ls -d openwrt/bin/packages/*/ | head -n 1)
          # Create the final directory structure in a temporary 'dist' folder
          mkdir -p dist/${{ matrix.openwrt_version }}/${{ matrix.target_subtarget }}
          rsync -av ${TARGET_DIR}/* dist/${{ matrix.openwrt_version }}/${{ matrix.target_subtarget }}/
          cp ./openwrt/key-build.pub dist/${{ matrix.openwrt_version }}/
          
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: dist

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download all built packages
        uses: actions/download-artifact@v4
        with:
          name: packages
          path: ./dist

      - name: Create a root index.html file
        run: |
          cd dist
          echo '<!DOCTYPE html><html><head><title>PeDitXOS Repository</title><style>body{font-family: sans-serif; padding: 2em;}</style></head><body>' > index.html
          echo '<h1>PeDitXOS Repository</h1>' >> index.html
          echo '<h2>Available OpenWrt Versions:</h2><ul>' >> index.html
          
          for dir in $(find . -maxdepth 1 -type d -not -name '.*' -not -name '.' | sort); do
            version_name=$(basename "$dir")
            echo "<li><a href=\"$version_name/\">$version_name</a></li>" >> index.html
          done
          
          echo '</ul>' >> index.html
          
          find . -name 'key-build.pub' -print -exec cp {} ./key-build.pub \; -quit
          
          echo '<h3>Public Signing Key: <a href="key-build.pub">key-build.pub</a></h3>' >> index.html
          echo '</body></html>' >> index.html

      - name: Deploy to main repository via Deploy Key
        # This action securely pushes the build artifacts to your main repository's 'repo' branch.
        uses: peaceiris/actions-gh-pages@v4
        with:
          # The private key we stored in the builder repository's secrets
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          # The target repository on your main account (e.g., peditx/PeDitXOS-Repository)
          external_repository: peditx/PeDitXOS-Repository 
          publish_dir: ./dist
          publish_branch: repo
          force_orphan: true
          cname: repo.peditxos.ir
          
      - name: Final Check
        run: echo "Deployment to peditx/PeDitXOS-Repository 'repo' branch complete. Cloudflare Pages will now publish the changes."

